server:
  port: 8080
  domain: http://127.0.0.1:8080
  tomcat:
    connection-timeout: 600000
    threads:
      max: 200
    max-connections: 10000
    accept-count: 1000
    max-http-form-post-size: 104857600
    keep-alive-timeout: 600000

spring:
  profiles:
    active: @platform@,@deployment@,@db.type@
  application:
    name: aigc-platform-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 101MB
  mvc:
    async:
      request-timeout: 600000

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:aigc_platform.db
    username:
    password:
  comfyui:
      # 主机地址 默认127.0.0.1
      host: 127.0.0.1
      # comfyui端口号 默认8188
      port: 8188
      # comfyui会话id 默认随机生成UUID
      client-id: test
      # 提交绘图任务时，如果Comfyui内部有非当前服务提交的任务时是否自动取消
      auto-clear-task: true
      queue:
        # 任务队列类型 目前支持: queue(阻塞队列)、rabbit 后续支持: rocket、kafka、custom
        type: thread

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

application:
  version: @project.version@

---
spring:
  config:
    activate:
      on-profile: sqlite
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:aigc_platform.db
    username:
    password:

